// deployer_ost.go
//
// 本文件是 Deployer 接口针对 OpenSteamTool 的实现。
//
// 工作方式极简：把生成的 .lua 脚本原子写入 <Steam>/config/lua/，
// 剩下的全交给 OST——它的 LuaFileWatcher 会在 500ms 内检测到变更、
// 解析脚本、自动获取 manifest 与 depot 密钥、刷新 Steam 库界面。
// 本工具既不需要通知 OST，也不需要等待确认，更不必关闭 Steam。
//
// 生成脚本的格式约定（依据 OST 源码分析）：
//   - 函数名大小写无关，统一用小写 addappid
//   - addappid 的第二参数被 OST 完全忽略，故只输出 AppID 与密钥两种形态
//   - 携带密钥的条目输出三参数形式，无密钥的输出单参数形式

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// OSTDeployer 是面向 OpenSteamTool 的部署器实现。
//
// 通过 NewOSTDeployer 创建。steamPath 在构造时固定，若用户中途
// 修改了 Steam 路径，调用方应重新构造一个实例而非原地修改字段。
type OSTDeployer struct {
	steamPath string
	logger    *Logger
}

// 编译期断言：确保 OSTDeployer 完整实现了 Deployer 接口。
// 接口新增方法时，此处会立即报错而非等到运行时才发现。
var _ Deployer = (*OSTDeployer)(nil)

// NewOSTDeployer 创建一个 OpenSteamTool 部署器。
//
// 参数：
//   - steamPath: Steam 安装根目录，不校验有效性——真正的校验发生在
//     写入时，此时才能给出准确的错误原因
//   - logger:    日志记录器，可为 nil
func NewOSTDeployer(steamPath string, logger *Logger) *OSTDeployer {
	return &OSTDeployer{
		steamPath: steamPath,
		logger:    logger,
	}
}

// Name 返回注入器名称。
func (d *OSTDeployer) Name() string {
	return "OpenSteamTool"
}

// DeployDir 返回 OST 监控的 Lua 脚本目录完整路径。
//
// 示例返回值：C:\Program Files (x86)\Steam\config\lua
//
// NOTE: OST 支持通过自身的 toml 配置追加额外监控目录，但本工具
// 只使用默认目录——读取注入器的配置文件属于越界行为。
func (d *OSTDeployer) DeployDir() string {
	return filepath.Join(d.steamPath, ConfigDir, OSTLuaDirName)
}

// luaFileName 生成指定游戏的清单脚本文件名。
//
// 命名格式为 <清洗后的游戏名>_<主AppID>.lua。附加 AppID 的原因有两个：
// 一是同名游戏（重制版、区域版本）不会互相覆盖；二是 Remove 时可以
// 仅凭 AppID 反查文件，无需记住当初的游戏名。
func (d *OSTDeployer) luaFileName(gameName, mainAppID string) string {
	safeName := sanitizeFileName(gameName)
	return fmt.Sprintf("%s_%s%s", safeName, mainAppID, LuaFileExt)
}

// logf 在 logger 可用时记录信息级日志。
func (d *OSTDeployer) logf(format string, args ...any) {
	if d.logger != nil {
		d.logger.Info(format, args...)
	}
}

// warnf 在 logger 可用时记录警告级日志。
func (d *OSTDeployer) warnf(format string, args ...any) {
	if d.logger != nil {
		d.logger.Warn(format, args...)
	}
}

// buildLuaScript 根据清单包与用户选择生成 OST 可解析的 Lua 脚本。
//
// 参数：
//   - gp:          已解析的清单包
//   - selectedIDs: 用户勾选的 DLC AppID 列表；为空表示只注册主游戏
//
// 生成内容的顺序有意固定为「主游戏 → Depot 密钥 → DLC」：
// OST 逐行执行脚本，主游戏先注册可确保后续条目挂到正确的应用下。
//
// 每次生成的内容对相同输入是稳定的（不含时间戳等易变信息），
// 这样重复部署同一套选择不会产生内容差异，便于用户 diff 排查。
func (d *OSTDeployer) buildLuaScript(gp *GamePackage, selectedIDs []string) string {
	var b strings.Builder

	b.WriteString("-- Generated by kazeusa (风兔盒)\n")
	b.WriteString(fmt.Sprintf("-- Game: %s\n", gp.GameName))
	b.WriteString(fmt.Sprintf("-- AppID: %s\n", gp.MainAppID))
	b.WriteString("--\n")
	b.WriteString("-- 本文件由工具自动生成，手动修改可能在下次部署时被覆盖。\n\n")

	// 主游戏必须最先注册。
	b.WriteString(fmt.Sprintf("addappid(%s)\n", gp.MainAppID))

	// Depot 密钥：OST 凭此解密清单并下载内容。
	// 无密钥的 Depot 不输出——OST 会自行尝试从上游 API 获取。
	if len(gp.Depots) > 0 {
		b.WriteString("\n-- Depots\n")
		for _, depot := range gp.Depots {
			if depot.DecryptionKey == "" {
				continue
			}
			b.WriteString(fmt.Sprintf("addappid(%s, 1, %q)\n",
				depot.DepotID, depot.DecryptionKey))
		}
	}

	// DLC：仅输出用户勾选的条目。
	selected := toSet(selectedIDs)
	if len(selected) > 0 {
		b.WriteString("\n-- DLCs\n")
		for _, dlc := range gp.DLCs {
			if _, ok := selected[dlc.AppID]; !ok {
				continue
			}
			b.WriteString(d.formatDLCLine(&dlc))
		}
	}

	return b.String()
}

// formatDLCLine 生成单个 DLC 的 addappid 调用语句。
//
// 携带密钥时输出三参数形式，否则输出单参数形式。
// 第二参数固定填 1——OST 源码中该参数被完全忽略，填任何值都不影响
// 行为，保留它只是为了与社区流传的清单脚本格式保持视觉一致。
//
// DLC 名称以行尾注释形式附上，方便用户直接阅读脚本了解装了什么。
func (d *OSTDeployer) formatDLCLine(dlc *DLCInfo) string {
	comment := ""
	if dlc.Name != "" {
		comment = fmt.Sprintf("  -- %s", sanitizeLuaComment(dlc.Name))
	}

	if dlc.HasKey && dlc.DecryptionKey != "" {
		return fmt.Sprintf("addappid(%s, 1, %q)%s\n",
			dlc.AppID, dlc.DecryptionKey, comment)
	}
	return fmt.Sprintf("addappid(%s)%s\n", dlc.AppID, comment)
}

// sanitizeLuaComment 清洗字符串使其可安全用作 Lua 行尾注释。
//
// 换行符会让注释提前结束、后半段变成非法语句，故必须替换。
// 这不是理论风险——清单脚本的游戏名来自不可控的第三方来源。
func sanitizeLuaComment(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return strings.TrimSpace(s)
}

// toSet 将字符串切片转为集合，用于 O(1) 的成员判断。
//
// DLC 数量可达数百，逐个线性查找会退化为 O(n²)。
func toSet(items []string) map[string]struct{} {
	set := make(map[string]struct{}, len(items))
	for _, item := range items {
		if item != "" {
			set[item] = struct{}{}
		}
	}
	return set
}

// ============================================================
// Deployer 接口实现
// ============================================================

// Deploy 生成清单脚本并原子写入 OST 的监控目录。
//
// 参数：
//   - gp:          已解析的清单包，MainAppID 不可为空
//   - selectedIDs: 用户勾选的 DLC AppID 列表，可为空
//
// 返回值：
//   - string: 部署后的文件完整路径
//   - error:  Steam 路径未设置、清单包无效或写入失败时返回
//
// 写入完成后不做任何后续动作：OST 的 LuaFileWatcher 会在 500ms 内
// 感知到新文件，自行解析并刷新 Steam 库，用户无需重启 Steam。
func (d *OSTDeployer) Deploy(gp *GamePackage, selectedIDs []string) (string, error) {
	if d.steamPath == "" {
		return "", fmt.Errorf("Steam 路径未设置，无法部署")
	}
	if gp == nil || gp.MainAppID == "" {
		return "", ErrEmptyPackage
	}

	target := filepath.Join(d.DeployDir(), d.luaFileName(gp.GameName, gp.MainAppID))
	script := d.buildLuaScript(gp, selectedIDs)

	// atomicWriteFile 内部完成目录创建与 tmp+rename 提交，
	// 确保 OST 只会收到一次事件且读到完整内容。
	if err := atomicWriteFile(target, []byte(script)); err != nil {
		if d.logger != nil {
			d.logger.Error("清单部署失败 %s: %v", target, err)
		}
		return "", fmt.Errorf("部署清单文件失败: %w", err)
	}

	d.logf("清单已部署: %s（主游戏 %s，DLC %d 项）",
		target, gp.MainAppID, len(selectedIDs))
	return target, nil
}

// Remove 删除指定游戏的清单脚本。
//
// 参数：
//   - mainAppID: 主游戏 AppID，用于反查文件
//
// 返回值：
//   - error: Steam 路径未设置、AppID 为空或删除失败时返回。
//     目标文件本就不存在时返回 nil（幂等）
//
// 由于文件名包含游戏名而调用方可能只知道 AppID，此处采用扫描目录
// 匹配 `_<AppID>.lua` 后缀的方式定位，而非要求调用方提供完整文件名。
// 这也顺带处理了用户手动改过游戏名的情况。
//
// 删除后 OST 会在 500ms 内感知并将游戏从 Steam 库中移除。
func (d *OSTDeployer) Remove(mainAppID string) error {
	if d.steamPath == "" {
		return fmt.Errorf("Steam 路径未设置，无法移除")
	}
	if mainAppID == "" {
		return fmt.Errorf("AppID 不能为空")
	}

	dir := d.DeployDir()
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			// 目录不存在意味着从未部署过任何东西，视为已达成目标状态。
			d.logf("部署目录不存在，无需移除: %s", dir)
			return nil
		}
		return fmt.Errorf("读取部署目录失败 %s: %w", dir, err)
	}

	suffix := "_" + mainAppID + LuaFileExt
	removed := 0

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), suffix) {
			continue
		}

		path := filepath.Join(dir, entry.Name())
		if err := os.Remove(path); err != nil {
			// 单个文件删除失败不中断整体流程：可能是被占用的残留，
			// 继续处理其余匹配项，最终以是否有成功删除来判定结果。
			d.warnf("删除清单文件失败 %s: %v", path, err)
			continue
		}
		removed++
		d.logf("清单已移除: %s", path)
	}

	if removed == 0 {
		d.logf("未找到 AppID %s 对应的清单文件，无需移除", mainAppID)
	}
	return nil
}
