// lua_match_test.go
//
// 覆盖清单脚本的文本匹配逻辑。这些函数的正确性直接决定「哪些 DLC 显示
// 为已安装」与「卸载是否彻底」，且失效方式均为静默返回错误结果而非报错，
// 故以测试锁定行为。

package main

import (
	"reflect"
	"sort"
	"testing"
)

func TestLuaContainsAppID(t *testing.T) {
	const script = `
addappid(2399830, 1, "abc")
addappid( 2827030 )
setManifestid(2849450, "123", 456)
-- addappid(9999999)  已排除的 DLC
`

	cases := []struct {
		name  string
		appID string
		want  bool
	}{
		{"三参数形式", "2399830", true},
		{"参数含空格", "2827030", true},
		{"仅出现于 setManifestid 而无 addappid", "2849450", false},
		{"被注释的调用", "9999999", false},
		{"完全不存在", "1111111", false},
		// 子串误匹配是最危险的失效方式：239983 是 2399830 的前缀，
		// 若正则漏了边界约束便会把它判为已安装。
		{"前缀子串不得误匹配", "239983", false},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := luaContainsAppID(script, c.appID); got != c.want {
				t.Errorf("luaContainsAppID(%q) = %v, 期望 %v", c.appID, got, c.want)
			}
		})
	}
}

func TestLuaDeclaredAppIDs(t *testing.T) {
	const script = `
-- Generated by kazeusa
addappid(2399830, 1, "key")
addappid(2399831, 1, "key")
setManifestid(2399831, "gid", 100)
addappid(2827030)
addappid(2827030, 1, "key")
-- addappid(8888888)  已排除
`

	got := luaDeclaredAppIDs(script)
	sort.Strings(got)

	want := []string{"2399830", "2399831", "2827030"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("luaDeclaredAppIDs() = %v, 期望 %v", got, want)
	}
}

// 空切片而非 nil 是硬约束：Wails 将 nil 切片序列化为 JSON null，
// 前端遍历时会抛异常。
func TestLuaDeclaredAppIDsReturnsEmptySlice(t *testing.T) {
	got := luaDeclaredAppIDs("-- 全是注释\n")
	if got == nil {
		t.Fatal("返回了 nil 切片，会被序列化为 JSON null")
	}
	if len(got) != 0 {
		t.Errorf("期望空切片，实际 %v", got)
	}
}
