// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSteamPath():Promise<string>;

export function InstallDLCs(arg1:main.GamePackage,arg2:Array<string>):Promise<main.OperationResult>;

export function ProcessDroppedFile(arg1:string,arg2:Array<number>):Promise<main.GamePackage>;

export function ProcessZipFile(arg1:string):Promise<main.GamePackage>;

export function RemoveAllDLCs(arg1:main.GamePackage):Promise<main.OperationResult>;

export function SelectDirectory():Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetSteamPath(arg1:string):Promise<void>;
