// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<main.OperationResult>;

export function DetectEnvironment():Promise<main.DetectorResult>;

export function FindHistory(arg1:string):Promise<main.GameRecord>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDeployDir():Promise<string>;

export function GetHistory():Promise<Array<main.GameRecord>>;

export function GetLogPath():Promise<string>;

export function GetSteamPath():Promise<string>;

export function InstallDLCs(arg1:main.GamePackage,arg2:Array<string>):Promise<main.OperationResult>;

export function OpenDataDir():Promise<main.OperationResult>;

export function ProcessDroppedFile(arg1:string,arg2:Array<number>):Promise<main.GamePackage>;

export function ProcessZipFile(arg1:string):Promise<main.GamePackage>;

export function RemoveDLCs(arg1:string):Promise<main.OperationResult>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.OperationResult>;

export function SelectDirectory():Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetSteamPath(arg1:string):Promise<main.OperationResult>;
