// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DetectEnvironment() {
  return window['go']['main']['App']['DetectEnvironment']();
}

export function DownloadFromRepo(arg1, arg2) {
  return window['go']['main']['App']['DownloadFromRepo'](arg1, arg2);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function FindHistory(arg1) {
  return window['go']['main']['App']['FindHistory'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDeployDir() {
  return window['go']['main']['App']['GetDeployDir']();
}

export function GetGameDetail(arg1) {
  return window['go']['main']['App']['GetGameDetail'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetMSiteStats() {
  return window['go']['main']['App']['GetMSiteStats']();
}

export function GetPackage(arg1) {
  return window['go']['main']['App']['GetPackage'](arg1);
}

export function GetReleasePageURL() {
  return window['go']['main']['App']['GetReleasePageURL']();
}

export function GetSteamPath() {
  return window['go']['main']['App']['GetSteamPath']();
}

export function InstallDLCs(arg1, arg2) {
  return window['go']['main']['App']['InstallDLCs'](arg1, arg2);
}

export function LookupRepos(arg1) {
  return window['go']['main']['App']['LookupRepos'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProcessDroppedFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessDroppedFile'](arg1, arg2);
}

export function ProcessZipFile(arg1) {
  return window['go']['main']['App']['ProcessZipFile'](arg1);
}

export function RemoveDLCs(arg1) {
  return window['go']['main']['App']['RemoveDLCs'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanDeployed() {
  return window['go']['main']['App']['ScanDeployed']();
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectZipFile() {
  return window['go']['main']['App']['SelectZipFile']();
}

export function SetRepoToken(arg1, arg2) {
  return window['go']['main']['App']['SetRepoToken'](arg1, arg2);
}

export function SetSteamPath(arg1) {
  return window['go']['main']['App']['SetSteamPath'](arg1);
}
