// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSteamPath() {
  return window['go']['main']['App']['GetSteamPath']();
}

export function InstallDLCs(arg1, arg2) {
  return window['go']['main']['App']['InstallDLCs'](arg1, arg2);
}

export function ProcessDroppedFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessDroppedFile'](arg1, arg2);
}

export function ProcessZipFile(arg1) {
  return window['go']['main']['App']['ProcessZipFile'](arg1);
}

export function RemoveAllDLCs(arg1) {
  return window['go']['main']['App']['RemoveAllDLCs'](arg1);
}

export function SelectZipFile() {
  return window['go']['main']['App']['SelectZipFile']();
}
