// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearHistory():Promise<main.OperationResult>;

export function DetectEnvironment():Promise<main.DetectorResult>;

export function DownloadFromRepo(arg1:string,arg2:string):Promise<main.GamePackage>;

export function ExportDiagnostics():Promise<main.DiagnosticsResult>;

export function FindHistory(arg1:string):Promise<main.GameRecord>;

export function GetAppVersion():Promise<string>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDeployDir():Promise<string>;

export function GetGameDetail(arg1:string):Promise<main.GameDetail>;

export function GetHistory():Promise<Array<main.GameRecord>>;

export function GetLogPath():Promise<string>;

export function GetMSiteStats():Promise<main.MSiteStats>;

export function GetPackage(arg1:string):Promise<main.StoredPackage>;

export function GetReleasePageURL():Promise<string>;

export function GetSteamPath():Promise<string>;

export function InstallDLCs(arg1:main.GamePackage,arg2:Array<string>):Promise<main.OperationResult>;

export function InstallFromTrial(arg1:string,arg2:string):Promise<main.GamePackage>;

export function LookupRepos(arg1:string):Promise<Array<string>>;

export function OpenDataDir():Promise<main.OperationResult>;

export function OpenURL(arg1:string):Promise<main.OperationResult>;

export function ProcessDroppedFile(arg1:string,arg2:Array<number>):Promise<main.GamePackage>;

export function ProcessZipFile(arg1:string):Promise<main.GamePackage>;

export function RemoveDLCs(arg1:string):Promise<main.OperationResult>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.OperationResult>;

export function ScanDeployed():Promise<Array<main.DeployedEntry>>;

export function SearchGames(arg1:string):Promise<Array<main.GameSearchResult>>;

export function SelectDirectory():Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetRepoToken(arg1:string,arg2:string):Promise<main.OperationResult>;

export function SetSteamPath(arg1:string):Promise<main.OperationResult>;

export function TrialOneSource(arg1:string,arg2:string):Promise<main.SourceTrial>;

export function TrialSources(arg1:string,arg2:boolean):Promise<main.TrialReport>;
